### PR TITLE
Allow for remote servers to connect to cluster

### PR DESCRIPTION
**Pull request by happilymarrieddad**
I was hoping you'd approve the ability to specify a specific broker cluster should a user need it.

### CODE REVIEW

**Comment by happilymarrieddad** [comment]
Maybe a better way to do this is grab the broker cluster IP and host from the state-server but I have no idea how to do that.

**Comment by happilymarrieddad** [comment]
@jon i can see how you wouldnt like this because it essentially hardcodes a server to one broker server instead of allowing the state server to dynamically assign a broker server but somewhere that is broken. Just go to aws spin up 3 servers and try it. I dont know scc well enough to track down where the state server is not sending the correct ip of a broker server. It is always 127.0.0.1 which doesnt work if the application server isnt on the same machine as the broker state server. I hope that makes sense. Thanks!

**Comment by happilymarrieddad** [comment]
@jondubois Hey man, this is so the dev can specify a specific broker at start if they need it. One of the things I noticed is that the IP of the broker server is relative to the state server so if they are behind different availability zones on AWS then the IP that the app server sees is different than the IP broadcasted back to the state server. I think at some point, we need to pass from the broker server a different IP to the state server so that when it broadcasts the IP of the broker server to the app server it works behind say AWS' availability zones.

**Comment by jondubois** [comment]
@happilymarrieddad I can't merge PR because it doesn't account for the fact that there may be multiple back end broker servers. The logic logic in this repo is actually very complicated and desperately needs more comments to explain what is happening so it's a good attempt ;)

The `uri` passed here https://github.com/SocketCluster/sc-cluster-broker-client/pull/1/files#diff-93d530dd373561824113ae069f0bced6R30 comes from the state server (the state server sends sc-cluster-broker-client a list of URIs which point to all scc-brokers in our cluster) - The `breakDownURI` function will be called multiple times for each of those broker URIs (and again, there may be multiple of them).

In SCC, every backend scc-broker connects to the state server and reports their own `instanceIp` (IP address). If an scc-broker doesn't report its instanceIp, then the state server will use the default remoteAddress for that scc-broker (which may or may not be suitable depending on the network infrastructure).

You can customize the ip address reported by each scc-broker by setting an `SCC_INSTANCE_IP` environment variable on the machines on which the scc-brokers run. See https://github.com/SocketCluster/sc-cluster-broker-server/blob/master/server.js#L8

If you look here: https://github.com/SocketCluster/sc-cluster-broker-server/blob/master/server.js#L88 - This is where the scc-broker reports its IP address to the state server (which the state server will then pass on to all sc instances in the cluster). If you look just a few lines above that, you can see where the `instanceIp` is being set here: https://github.com/SocketCluster/sc-cluster-broker-server/blob/master/server.js#L81

sc-cluster-broker-client (this repo) is basically the backend-facing client which regular SC instances use to connect to the cluster of backend scc-brokers.

**Comment by jondubois** [comment]
In the Kubernetes config file for the scc-broker, we pass a custom `SCC_INSTANCE_IP` environment variable which is the `status.podIP` provided by Kubernetes. https://github.com/SocketCluster/socketcluster/blob/master/kubernetes/scc-broker-deployment.yaml#L20-L23 so you'd have to do something similar when running it stand-alone (outside of K8s)

**Comment by happilymarrieddad** [comment]
Thanks so much for taking the time to look at it!

**Pull request closed without merging**
